services:
  web:
    image: gaetan1303/snapcat:latest
    ports:
      - "8888:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: snapcatuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: snapcatdb
      