services:
  web:
    image: gaetan1303/snapcat:latest
    ports:
      - "8888:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snapcatdb 
    volumes:
      - db_data:/var/lib/mysql 


volumes:
  db_data: