version: '3.8'
services:
  web:
    image: gaetan1303/snapcat:latest
    ports:
      - "80:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: snapcat
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: snapcatdb

