version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_USER: snapcatuser
      MYSQL_PASSWORD: snapcatpass
      MYSQL_DATABASE: snapcat
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: snapcat
      MYSQL_USER: snapcatuser
      MYSQL_PASSWORD: snapcatpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

